--------------------------------------------------------
-- Archivo creado  - sábado-septiembre-26-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence DEPARTMENTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."DEPARTMENTS_SEQ"  MINVALUE 1 MAXVALUE 9990 INCREMENT BY 10 START WITH 280 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYEES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."EMPLOYEES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 207 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HUERTO_ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."HUERTO_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LOCATIONS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."LOCATIONS_SEQ"  MINVALUE 1 MAXVALUE 9900 INCREMENT BY 100 START WITH 3300 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table HUERTOSEX
--------------------------------------------------------

  CREATE TABLE "HR"."HUERTOSEX" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"IDUSUARIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HR"."HUERTOSEX"."ID" IS 'IDENTIFICADOR DEL HUERTO';
   COMMENT ON COLUMN "HR"."HUERTOSEX"."NOMBRE" IS 'NOMBRE DEL HUERTO';
   COMMENT ON COLUMN "HR"."HUERTOSEX"."IDUSUARIO" IS 'IDENTIFICADOR DEL PROPIETARIO';
--------------------------------------------------------
--  DDL for Table MACETASEX
--------------------------------------------------------

  CREATE TABLE "HR"."MACETASEX" 
   (	"ID" NUMBER, 
	"IDTIPO" NUMBER, 
	"MCACOMPLETA" NUMBER(1,0) DEFAULT 0, 
	"IDHUERTO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLANTASEX
--------------------------------------------------------

  CREATE TABLE "HR"."PLANTASEX" 
   (	"ID" NUMBER, 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"IDUSUARIO" NUMBER, 
	"IDMACETA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HR"."PLANTASEX"."ID" IS 'IDENTIFICADOR DE LA PLANTA';
   COMMENT ON COLUMN "HR"."PLANTASEX"."NOMBRE" IS 'NOMBRE DE LA PLANTA';
   COMMENT ON COLUMN "HR"."PLANTASEX"."IDUSUARIO" IS 'IDENTIFICADOR DEL PROPIETARIO DE LA PLANTA';
   COMMENT ON COLUMN "HR"."PLANTASEX"."IDMACETA" IS 'IDENTIFICADOR DE LA MACETA';
--------------------------------------------------------
--  DDL for Table USUARIOSEX
--------------------------------------------------------

  CREATE TABLE "HR"."USUARIOSEX" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(8 BYTE), 
	"PASSWORD" VARCHAR2(8 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"APELLIDOS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index HUERTOSEX_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."HUERTOSEX_PK" ON "HR"."HUERTOSEX" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MACETASEX_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."MACETASEX_PK" ON "HR"."MACETASEX" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PLANTASEX_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."PLANTASEX_PK" ON "HR"."PLANTASEX" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIOSEX_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."USUARIOSEX_PK" ON "HR"."USUARIOSEX" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
/
--------------------------------------------------------
--  Constraints for Table HUERTOSEX
--------------------------------------------------------

  ALTER TABLE "HR"."HUERTOSEX" ADD CONSTRAINT "HUERTOSEX_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."HUERTOSEX" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."HUERTOSEX" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "HR"."HUERTOSEX" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MACETASEX
--------------------------------------------------------

  ALTER TABLE "HR"."MACETASEX" ADD CONSTRAINT "MACETASEX_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."MACETASEX" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."MACETASEX" MODIFY ("IDTIPO" NOT NULL ENABLE);
  ALTER TABLE "HR"."MACETASEX" MODIFY ("MCACOMPLETA" NOT NULL ENABLE);
  ALTER TABLE "HR"."MACETASEX" MODIFY ("IDHUERTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLANTASEX
--------------------------------------------------------

  ALTER TABLE "HR"."PLANTASEX" ADD CONSTRAINT "PLANTASEX_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."PLANTASEX" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLANTASEX" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PLANTASEX" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOSEX
--------------------------------------------------------

  ALTER TABLE "HR"."USUARIOSEX" ADD CONSTRAINT "USUARIOSEX_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."USUARIOSEX" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HR"."USUARIOSEX" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table HUERTOSEX
--------------------------------------------------------

  ALTER TABLE "HR"."HUERTOSEX" ADD CONSTRAINT "HUERTOSEX_FK1" FOREIGN KEY ("IDUSUARIO")
	  REFERENCES "HR"."USUARIOSEX" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MACETASEX
--------------------------------------------------------

  ALTER TABLE "HR"."MACETASEX" ADD CONSTRAINT "MACETASEX_FK1" FOREIGN KEY ("IDHUERTO")
	  REFERENCES "HR"."HUERTOSEX" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLANTASEX
--------------------------------------------------------

  ALTER TABLE "HR"."PLANTASEX" ADD CONSTRAINT "PLANTASEX_FK1" FOREIGN KEY ("IDMACETA")
	  REFERENCES "HR"."MACETASEX" ("ID") ENABLE;
  ALTER TABLE "HR"."PLANTASEX" ADD CONSTRAINT "PLANTASEX_FK2" FOREIGN KEY ("IDUSUARIO")
	  REFERENCES "HR"."USUARIOSEX" ("ID") ENABLE;
